### ISSUE TITLE
Blank screen after open bookmarked site in new tab

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#492]
Steps :
Save a site as bookmark
Open bookmarks
Hold the bookmark
open the bookmark in a new tab , 
The new tab opend but the page dosn't load

**Comment by scoute-dich** [comment]
I can not clearly reproduce this bug, but I also faced problems when opening new tabs. My problem is fixed, perhaps yours also.
[app-debug.zip](https://github.com/scoute-dich/browser/files/6466588/app-debug.zip)

**Comment by islam2hamy** [comment]
<a href="https://ibb.co/L0Pqj86"><img src="https://i.ibb.co/zm5L9rb/IMG.jpg" alt="IMG" border="0"></a><a href="https://ibb.co/L0Pqj86"><img src="https://i.ibb.co/zm5L9rb/IMG.jpg" alt="IMG" border="0"></a>

**Comment by islam2hamy** [comment]
<a href="https://ibb.co/CwTDw0k"><img src="https://i.ibb.co/x2Rd25p/IMG.jpg" alt="IMG" border="0"></a>

**Comment by islam2hamy** [comment]
p.s :
Keyboard doesn't work in this release in the toolbar for the new tab

**Comment by scoute-dich** [comment]
This happens also when opening new tabs from start and history? Also this happens only with some entries or with all entries?

**Comment by islam2hamy** [comment]
This happens also when opening new tabs from start and history? 
Yes

Also this happens only with some entries or with all entries?
All

**Comment by islam2hamy** [comment]
Btw: 
If you opened the site in a new tab (background)
It will open

**Comment by scoute-dich** [comment]
You mean the intended behavior: it loads and opens in the background?

I'm going camping this weekend. So you won't hear something from me for a few days. In the meantime I released an update with latest fixes. If you want you can test it. Perhaps some of the issues are solved.

**Comment by islam2hamy** [comment]
If you use :
 open the site in a new tab (background) , and go to this tab , the site will work

**Comment by snoopymat** [comment]
I can confirm the behaviour, that @islam2hamy had reported:
What works:
1) Loading bookmark in foreground by tipping on bookmark in bookmark view.
2) Loading bookmark in background via long pressing bookmark in bookmark view and in context menu choosing option "New tab (background)".

What does **not** work:
3) Loading bookmark in foreground via long pressing bookmark in bookmark view and **in context menu** choosing option "New tab (**foreground**)". 
Then the view is empty. And: the address field still shows the URL, not the title of the web page. Seems as if the app still has not connected to the web server.

With FOSS Browser 7.4.3 under Android 8.1.0 and under Android 10 (EMUI)

**Comment by scoute-dich** [comment]
Is the problem solved with 7.4.4?

**Comment by islam2hamy** [comment]
No

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6600749/app-debug.apk.zip)
I made some changes in the code. Since I can not reproduce this issue, I'll need you to test. Thanks in advance.

_P.S.: Tell me also, which Android version you are using while testing._

**Comment by islam2hamy** [comment]
Not working
Android 7.1.2

**Comment by snoopymat** [comment]
Hello Gaukler Faun,

yesterday I had installed the app link of which you had posted on 4th June (it has version number 7.4.4).
In this version:
- issue #492 (Blank screen ...) still exists, and 
- issue #513 (New bookmarks ...) is fixed.

In the version 7.4.4 I had installed some days ago from F-Droid App Store:
- issue #492 (Blank screen ...) I did not test, and 
- issue #513 (New bookmarks ...) still exists.

I test on Smartphone with Android 8.1.0 Oreo with 5,2 " display.

Best Regards,
snoopymat

**Comment by scoute-dich** [comment]
I just released a new version (7.5) if this bug still is not solved, please report it here. Otherwise, I'll close this issue.

**Comment by islam2hamy** [comment]
Not solved

**Comment by scoute-dich** [comment]
I think it's the Android version. Perhaps you can test the following apk-file:
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6725087/app-debug.apk.zip)

**Comment by scoute-dich** [comment]
If this fix does not work, please tell me which Android version you are using. This seems to be the problem.

**Comment by islam2hamy** [comment]
> Not working
> Android 7.1.2
> Miui 11.0.2

Not working

**Comment by scoute-dich** [comment]
So, this one should work.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6731493/app-debug.apk.zip)

**Comment by islam2hamy** [comment]
Fixed  :)

**Comment by islam2hamy** [comment]
Fixed  :)

**Comment by scoute-dich** [comment]
It took long enough. 🥴
